In [4]:
a = r'raw string'
b = b'ASCII string'
c = u'unicode string'
print a, b, c

raw string ASCII string unicode string


In [16]:
#Tuple is immutable
empty = (1,2)
print empty

#List is mutable
empty = []

#Set is mutable
empty = set()
#print set('a')

(1, 2)


## DateTime 


In [1]:
import datetime as dt
import time as tm

In [2]:
tm.time()

1500582175.370893

In [4]:
date_now = dt.datetime.fromtimestamp(tm.time())
print date_now

2017-07-20 13:24:13.915911


In [8]:
date_now.year, date_now.month, date_now.day

(2017, 7, 20)

In [10]:
delta = dt.timedelta(100)
delta

datetime.timedelta(100)

In [12]:
today = dt.date.today()
today

datetime.date(2017, 7, 20)

In [14]:
today - delta

datetime.date(2017, 4, 11)

In [15]:
today > today - delta

True

## Python class

In [20]:
class Person:
    department = 'School of Information'
    
    def set_name(self, new_name):
        self.name = new_name
        
    def set_location(self, new_location):
        self.location = new_location


In [21]:
person = Person()
person.set_name('Jon Luu')
person.set_location('Oakland, CA')
print ('{} lives in {} and works in department {}'.format(person.name, person.location, person.department))

Jon Luu lives in Oakland, CA and works in department School of Information


In [23]:
store1 = [10.00, 11.00, 23.00, 2.34]
store2 = [12.00, 10.00, 32.00, 3.11]
cheapest = map(min, store1, store2)
cheapest

[10.0, 10.0, 23.0, 2.34]

In [27]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format (title, lastname)

list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [28]:
my_function = lambda a, b, c: a+b 

In [30]:
my_function(1, 2, 3)

3

In [31]:
my_list = []
for i in range(0,10):
    if i%2 == 0:
        my_list.append(i)
my_list

[0, 2, 4, 6, 8]

In [40]:
items = [1, 2, 3, 4, 5]
def sqr(x):
    return x**2

print list(map(sqr, items))
print list(map((lambda x: x**2), items))

[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25]


In [44]:
def square(x):
    return x**2

def cube(x):
    return x**3
def num(x):
    return x

functions = [num, square, cube]

for r in range(5):
    value = map(lambda x: x(r), functions)
    print value

[0, 0, 0]
[1, 1, 1]
[2, 4, 8]
[3, 9, 27]
[4, 16, 64]


In [45]:
f = lambda x, y : x**y
f(2,3)

8

In [52]:
def cel(T):
    return ((float(9)/5)*T + 32)

def far(T):
    return ((float(5)/9)*(T-32))

temp = (100.0, 32.0, 102.0, 75.0)

F = map(cel, temp)
C = map(far, F)

print F, C

[212.0, 89.6, 215.6, 167.0] [100.0, 32.0, 102.0, 75.0]


In [57]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'
id = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]
id[1015:1020]

['ak15', 'ak16', 'ak17', 'ak18', 'ak19']

## Numpy

In [58]:
import numpy as np

## Creating Arrays

In [60]:
my_list = [1, 2, 3, 4, 5]
x = np.array(my_list)
x

array([1, 2, 3, 4, 5])

In [63]:
y = np.array([[4,5,6,7,8], [11, 22, 33, 44,55]])
y

array([[ 4,  5,  6,  7,  8],
       [11, 22, 33, 44, 55]])

In [73]:
y.mean()
aa = np.arange(0, 30, 2)
aa

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [81]:
x = aa.reshape(3, 5)
x

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [88]:
o = np.linspace(1, 1.1, 10)
o

array([ 1.        ,  1.01111111,  1.02222222,  1.03333333,  1.04444444,
        1.05555556,  1.06666667,  1.07777778,  1.08888889,  1.1       ])

In [90]:
o.resize(2,5)
o

array([[ 1.        ,  1.01111111,  1.02222222,  1.03333333,  1.04444444],
       [ 1.05555556,  1.06666667,  1.07777778,  1.08888889,  1.1       ]])

In [99]:
print np.ones((3,4))
print np.zeros((2,3))
print np.zeros_like?

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [100]:
print np.zeros_like(o)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [105]:
print np.eye(2)
print np.diag(o)

[[ 1.  0.]
 [ 0.  1.]]
[ 1.          1.06666667]


In [104]:
print np.array([1,2,3]*3)
print np.repeat([1,2,3], 3)

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


In [107]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [109]:
print np.vstack([p, p*2])

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]


In [115]:
a = np.array([1,2,3,4,5,2,1,4,-2,-45,-2,5,9])
print a.sum()
print a.min()
print a.mean()
print a.std()
print a.argmax()

-13
-45
-1.0
13.0147844924
12


# Indexing and Slicing

In [137]:
r =np.arange(25)
r.resize((5,5))
r

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [138]:
print r[2,3]
print r[2, 3:6]

13
[13 14]


In [141]:
r[r>12] = 30
r

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 30, 30],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30]])

In [144]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [145]:
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [148]:
r
r2 = r*2

In [149]:
for i, row in enumerate(r):
    print r[i]

[0 0 0 3 4]
[0 0 0 8 9]
[ 0  0  0 30 30]
[30 30 30 30 30]
[30 30 30 30 30]


In [150]:
for i, j in zip(r, r2):
    print (i, '+', j,  '=', i + j)

(array([0, 0, 0, 3, 4]), '+', array([0, 0, 0, 6, 8]), '=', array([ 0,  0,  0,  9, 12]))
(array([0, 0, 0, 8, 9]), '+', array([ 0,  0,  0, 16, 18]), '=', array([ 0,  0,  0, 24, 27]))
(array([ 0,  0,  0, 30, 30]), '+', array([ 0,  0,  0, 60, 60]), '=', array([ 0,  0,  0, 90, 90]))
(array([30, 30, 30, 30, 30]), '+', array([60, 60, 60, 60, 60]), '=', array([90, 90, 90, 90, 90]))
(array([30, 30, 30, 30, 30]), '+', array([60, 60, 60, 60, 60]), '=', array([90, 90, 90, 90, 90]))


# Data Structures of Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
animals = ['Tiger', 'Cat', 'Rat']
pd.Series(animals)

0    Tiger
1      Cat
2      Rat
dtype: object

In [3]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [4]:
numbers = [1, 2, None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [5]:
import numpy as np
np.nan == None

False

In [6]:
np.nan == np.nan

False

In [7]:
np.isnan(np.nan)

True

In [12]:
sports = {'Football': 'England', 'Golf': 'USA', 'Swim': 'Canada'}
s = pd.Series(sports)
s

Football    England
Golf            USA
Swim         Canada
dtype: object

In [15]:
s.index

Index([u'Football', u'Golf', u'Swim'], dtype='object')

In [17]:
s = pd.Series(['Football', 'Golf', 'Swim'], ['England', 'USA', 'Canada'])
s

England    Football
USA            Golf
Canada         Swim
dtype: object

##  Querying Series

In [19]:
sports = {'Football': 'England', 'Golf': 'USA', 'Swim': 'Canada'}
s = pd.Series(sports)
s

Football    England
Golf            USA
Swim         Canada
dtype: object

In [20]:
s.iloc[2]

'Canada'

In [21]:
s.loc['Golf']

'USA'

In [22]:
s[2]

'Canada'

In [23]:
s['Golf']

'USA'

In [34]:
sports = {99: 'Russia',
         100: 'Germany',
         101: 'Lativa',
         102: 'Poland'}
ss = pd.Series(sports)
ss

99      Russia
100    Germany
101     Lativa
102     Poland
dtype: object

In [35]:
#ss[0] ==> generate key error because we don't have 0 index, so we can use ss.iloc[0]

In [36]:
ss.iloc[0]

'Russia'

In [39]:
ss.loc[99]

'Russia'

In [40]:
ss[99]

'Russia'

In [41]:
num = pd.Series([12, 45, 67, 98, 100])
num

0     12
1     45
2     67
3     98
4    100
dtype: int64

In [42]:
total = 0
for n in num:
    total = total+n
print total

322


In [43]:
import numpy as np
total = np.sum(num)
print total

322


In [53]:
a = pd.Series(np.random.randint(0, 100, 10000))
a.head()

0    52
1    37
2    26
3    71
4    99
dtype: int64

In [54]:
len(a)

10000

In [55]:
%%timeit -n 100
summary = 0
for item in a:
        summary += item


100 loops, best of 3: 2.21 ms per loop


In [56]:
%%timeit -n 100
summary = np.sum(a)

100 loops, best of 3: 71.7 µs per loop


In [57]:
a +=2
a.head()

0     54
1     39
2     28
3     73
4    101
dtype: int64

In [ ]:
for label, value in a.iteritems():
    a.set_value(label, value+2)
a.head()

In [ ]:
%%timeit -n 100
s = pd.Series(np.random.randint(0, 100, 10000))
for label, value in s.iteritems():
    s.loc[label] = value+2

In [ ]:
%%timeit -n 100
s = pd.S

## DataFrame

In [77]:
import pandas as pd
purchase_1 = pd.Series({'Name' : 'Chris', 
                       'Item Purchased' : 'Dog Food', 
                       'Cost' : 22.50})
purchase_2 = pd.Series({'Name' : 'Kevin',
                       'Item Purchased' : 'Milk',
                       'Cost' : 3.89})
purchase_3 = pd.Series({'Name': 'Adam',
                       'Item Purchased' : 'Meat',
                       'Cost' : 11.49})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index = ['Store1', 'Store3', 'Store3'])
df

Cost Item Purchased   Name
Store1  22.50       Dog Food  Chris
Store3   3.89           Milk  Kevin
Store3  11.49           Meat   Adam

In [82]:
df.loc['Store3']

Cost Item Purchased   Name
Store3   3.89           Milk  Kevin
Store3  11.49           Meat   Adam

In [83]:
df.T

Store1 Store3 Store3
Cost                22.5   3.89  11.49
Item Purchased  Dog Food   Milk   Meat
Name               Chris  Kevin   Adam

In [84]:
df

Cost Item Purchased   Name
Store1  22.50       Dog Food  Chris
Store3   3.89           Milk  Kevin
Store3  11.49           Meat   Adam

In [86]:
df.loc['Store3']['Cost']

Store3     3.89
Store3    11.49
Name: Cost, dtype: float64

In [87]:
df.loc[: , ['Name', 'Cost']]

Name   Cost
Store1  Chris  22.50
Store3  Kevin   3.89
Store3   Adam  11.49

In [89]:
df.drop('Store3')

Cost Item Purchased   Name
Store1  22.5       Dog Food  Chris

In [90]:
df

Cost Item Purchased   Name
Store1  22.50       Dog Food  Chris
Store3   3.89           Milk  Kevin
Store3  11.49           Meat   Adam

In [92]:
copy_df = df.copy()
copy_df = copy_df.drop('Cost', axis = 1)
copy_df


Item Purchased   Name
Store1       Dog Food  Chris
Store3           Milk  Kevin
Store3           Meat   Adam

In [100]:
df['Location'] = None
df

Cost Item Purchased   Name Location
Store1  22.50       Dog Food  Chris     None
Store3   3.89           Milk  Kevin     None
Store3  11.49           Meat   Adam     None

## DataFrame Indexing and Loading

In [101]:
costs = df['Cost']
costs

Store1    22.50
Store3     3.89
Store3    11.49
Name: Cost, dtype: float64

In [104]:
costs +=2
costs

Store1    26.50
Store3     7.89
Store3    15.49
Name: Cost, dtype: float64

In [105]:
df

Cost Item Purchased   Name Location
Store1  26.50       Dog Food  Chris     None
Store3   7.89           Milk  Kevin     None
Store3  15.49           Meat   Adam     None

In [2]:
df.columns

Index([u'0', u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10',
       u'11', u'12', u'13', u'14', u'15'],
      dtype='object')

In [4]:
#for col in df.columns:
 #   print col

In [112]:
bf = pd.read_csv('billionaires.csv', index_col=2)
bf.head()

age            category  \
citizenship                              
Saudi Arabia    -1           Financial   
United States   34           Financial   
Brazil          59  Non-Traded Sectors   
Germany         61         New Sectors   
Hong Kong       -1           Financial   

                                         company.name company.type  \
citizenship                                                          
Saudi Arabia   Rolaco Trading and Contracting Company          new   
United States                    Fidelity Investments          new   
Brazil           Companhia Brasileira de Distribui?ao          new   
Germany                                    Ratiopharm          new   
Hong Kong                                       Swire          new   

              country code  founded from emerging           gdp  gender  \
citizenship                                                               
Saudi Arabia           SAU     1968          True  1.580000e+11    male   
United States          USA     1946          True  8.100000e+12  female   
Brazil                 BRA     1948          True  8.540000e+11    male   
Germany                DEU     1881          True  2.500000e+12    male   
Hong Kong              HKG     1816          True  1.600000e+11    male   

                         industry  ...                      name rank  \
citizenship                        ...                                  
Saudi Arabia     Money Management  ...    Abdul Aziz Al-Sulaiman  404   
United States    Money Management  ...           Abigail Johnson  145   
Brazil         Retail, Restaurant  ...   Abilio dos Santos Diniz  322   
Germany        Technology-Medical  ...             Adolf Merckle  388   
Hong Kong        Money Management  ...     Adrian and John Swire  162   

                                 region relationship              sector  \
citizenship                                                                
Saudi Arabia   Middle East/North Africa      founder        construction   
United States             North America     relation  investment banking   
Brazil                    Latin America     relation              retail   
Germany                          Europe     relation     pharmaceuticals   
Hong Kong                     East Asia     relation     trading company   

              was founder was political        wealth.type worth in billions  \
citizenship                                                                    
Saudi Arabia         True         False  self-made finance               1.0   
United States        True         False          inherited               2.5   
Brazil               True         False          inherited               1.2   
Germany              True         False          inherited               1.0   
Hong Kong            True         False          inherited               2.2   

               year  
citizenship          
Saudi Arabia   1996  
United States  1996  
Brazil         1996  
Germany        1996  
Hong Kong      1996  

[5 rows x 21 columns]

In [127]:
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])


df = df.set_index([df.index, 'Name'])
df.index.names = ['Location', 'Name']
df = df.append(pd.Series(data={'Cost': 3.00, 'Item Purchased': 'Kitty Food'}, name=('Store 2', 'Kevyn')))
df

Cost Item Purchased
Location Name                      
Store 1  Chris  22.5       Dog Food
         Kevyn   2.5   Kitty Litter
Store 2  Vinod   5.0      Bird Seed
         Kevyn   3.0     Kitty Food

In [12]:
import numpy as np
aa = np.arange(0, 36)
#print aa
x = aa.reshape(6,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [5]:
x[0:6,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [7]:
x[::7]

array([[0, 1, 2, 3, 4, 5]])

In [9]:
x[:,::7]


array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [10]:
x.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [5]:
import pandas as pd
df = pd.read_csv('olympics.csv')
df.head(3)

0         1     2     3     4      5         6     7     8  \
0                NaN  № Summer  01 !  02 !  03 !  Total  № Winter  01 !  02 !   
1  Afghanistan (AFG)        13     0     0     2      2         0     0     0   
2      Algeria (ALG)        12     5     2     8     15         3     0     0   

      9     10       11    12    13    14              15  
0  03 !  Total  № Games  01 !  02 !  03 !  Combined total  
1     0      0       13     0     0     2               2  
2     0      0       15     5     2     8              15

In [7]:
df.rename??